name: gwas_toolkit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - numba
  - tqdm
  - scikit-learn
  - pyarrow
  - bed-reader
  - jupyter
  - ipykernel
  - pip
  - pip:
      - bed-reader[sparse]
      - -e .
