name: gwas_toolkit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - numba
  - tqdm
  - scikit-learn
  - pyarrow
  - bed-reader
  - pip
  - pip:
      - git+https://github.com/ItsReces/gwas_toolkit.git#egg=gwas_toolkit