[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "gwas_toolkit"
version = "0.0.1"
description = "GWAS analysis utilities"
dependencies = [
    "numpy",
    "scipy",
    "numba",
    "tqdm",
    "scikit-learn",
    "pyarrow",
    "bed_reader"
]